### ISSUE TITLE
When executing the script, I encountered the following error. May I ask whether the 'REL' package is custom or a third-party？ But the 'REL' package was installed in my virtual environment.

### ISSUE THREAD

**Issue by half-fairy** [code-chendl/HFIR#1]
![image](https://user-images.githubusercontent.com/58975392/226148505-b8906c87-dcd2-4979-93ad-965526ee5c47.png)

/mm/VAuLT$ ./scripts/test-results.sh -t /data/twitter-tmsc -b /data/bloomberg-twitter-text-image -m /data/mvsa -c 0 -r 5
2023-03-19 08:57:38.432928: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "experiments/clsf_vault.py", line 8, in <module>
    from vault.models.vault import (
  File "/home/wy/wy/mm/VAuLT/vault/models/vault/__init__.py", line 1, in <module>
    from .dataset import (
  File "/home/wy/wy/mm/VAuLT/vault/models/vault/dataset.py", line 9, in <module>
    from vault.tmsc_utils.dataset import Twitter201XDataset, Twitter201XInfo
  File "/home/wy/wy/mm/VAuLT/vault/tmsc_utils/dataset.py", line 16, in <module>
    from vault.entity_linking import EntityLinker
  File "/home/wy/wy/mm/VAuLT/vault/entity_linking.py", line 7, in <module>
    from REL.ner import load_flair_ner, Cmns
ModuleNotFoundError: No module named 'REL'
![image](https://user-images.githubusercontent.com/58975392/226148656-87c89ecf-5971-4483-9087-2e40d67b619c.png)

**Comment by code-chendl** [comment]
Please try "pip install radboud-el" .
For more tutorials, you might refer to the following link:
https://rel.readthedocs.io/en/latest/

**Comment by code-chendl** [comment]
Please try "**pip install radboud-el**".
For more tutorials, you might refer to the following link:
https://rel.readthedocs.io/en/latest/

Thank you for your attention to our research.

**Comment by code-chendl** [comment]
Please try "**pip install radboud-el**".
For more tutorials, you might refer to the following link:
https://rel.readthedocs.io/en/latest/

Thank you for your attention to our research.
